### ISSUE TITLE
Geo type has additional reqId and ip when deployed

### ISSUE THREAD

**Issue by hls-app** [ktKongTong/hono-geo-middleware#1]
Not sure if this is the expected behaviour but the Geo object does not have definitions for the `reqId` and `ip` but shows up in prod.

Since it is not defined in the interface, I cannot use `const ip = getGeo(c).ip;`

As workaround, this is what I use now `const ip = c.req.header("CF-Connecting-IP") ?? "unknown";`

**Comment by hls-app** [comment]
Added the types: https://github.com/ktKongTong/hono-geo-middleware/pull/2

**Comment by ktKongTong** [comment]
see https://www.npmjs.com/package/hono-geo-middleware/v/0.1.2
